app_product:
    resource: "@AppBundle/Controller/ProductController.php"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
